### ISSUE TITLE
Add Google Analytics Events

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfrica/GenderGap.AFRICA#17]
## Description
Add events using google analytics to track how many people click the "Calculate" button and another that shows the country that was selected.

## Files

https://developers.google.com/analytics/devguides/collection/analyticsjs/events

## Tasks
- [ ] Add google analytics for tracking how many people hit the calculate button
- [ ] Add google analytics that tracks the country that was selected.

**Comment by DavidLemayian** [comment]
Moved to Pivotal.
