### ISSUE TITLE
[Fix] Fix dependancy in package.json

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfrica/GenderGap.AFRICA#25]
**Describe the bug**
Some of the packages on the package.json file seem to be deprecated and need an upgrade. When upgraded `gulp serve` command produces an error.

**To Reproduce**
Run the following commands

```
npm install
npm audit fix / npm audit fix --force
gulp serve

```

**Environment  tools**

```
Node 10.4.1
gulp 3.9.1
Npm 6.1.0

```

**Expected behavior**
Serve GenderGap.Africa on your local machine

**Screenshots**
![image](https://user-images.githubusercontent.com/3693563/42885025-9312d120-8aa8-11e8-8975-86dcd9ca5139.png)

**Comment by mtuchi** [comment]
@nerdlet 
Could paste your node version and npm version or yarn as well ? 
Thanks

**Comment by DavidLemayian** [comment]
Fixed.
